# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stig på GitHub
email: stigjb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Denne siden bruker jeg til å lære om å lage en nettside. Ikke hold
  pusten mens du venter på spennende innhold.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stigjb.github.io" # the base hostname & protocol for your site
twitter_username: stigjohan
github_username:  stigjb

# Build settings
markdown: kramdown
